# Multi-stage builds are a new feature requiring Docker 17.05 or higher on the daemon and client. 

# stage
FROM nginx:alpine

# COPY ./docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# stage END